# anything with wildcards needs quotes since wildcards might contain characters
# that are openly hostile to most shells
cluster:
  mkdir -p cluster_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-'{rule}-{wildcards}'
    --output='cluster_logs/{rule}/%j-{wildcards}.out'
    --time={resources.time}
default-resources:
  - partition=batch
  - mem_mb=1000
  - time="8:0:0"
set-resources:
  - label_vcf:mem_mb=32000
set-threads:
  - get_vcf_labels=1
  - train_ebm=4
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
